routes:
  - uris:
      - "/users"
      - "/products"
      - "/orders"
      - "/customers"
      - "/inventory/items"
      - "/transactions/sales"
      - "/reviews/products/latest"
      - "/categories/subcategories"
      - "/addresses/validate"
      - "/payments/process/creditcard"
      - "/notifications/push"
      - "/messages/inbox"
      - "/settings/profile"
      - "/cart/items/add"
      - "/wishlist/items/remove"
      - "/profile/preferences/update"
      - "/feedback/suggestions"
      - "/subscriptions/plans"
      - "/billing/invoices/summary"
      - "/events/calendar/upcoming"
      - "/files/documents/downloads"
      - "/support/tickets/create"
      - "/assets/images/gallery"
      - "/roles/permissions/manage"
      - "/licenses/software/activate"
      - "/tags/categories/list"
      - "/search/products/query"
      - "/locales/languages/translate"
      - "/teams/members/add"
      - "/projects/tasks/list"
      - "/calendar/events/schedule"
      - "/groups/threads/discussions"
      - "/threads/comments/post"
      - "/ratings/products/rate"
      - "/rankings/users/top"
      - "/favorites/items/add"
      - "/bookmarks/links/save"
      - "/suggestions/ideas/submit"
      - "/activities/logged/actions"
      - "/plans/subscriptions/manage"
      - "/schedules/appointments/book"
      - "/attendees/events/register"
      - "/checkins/attendees/scan"
      - "/checkouts/reservations/complete"
      - "/booking/availability/check"
      - "/facilities/rooms/list"
      - "/services/amenities/view"
      - "/promotions/deals/discounts"
      - "/coupons/vouchers/giftcards/rewards"
      - "/loyalty/referrals/earnings"
      - "/affiliates/commissions/report"
      - "/earnings/reports/analytics"
      - "/statistics/metrics/insights"
      - "/trends/charts/graphs"
      - "/dashboards/widgets/plugins"
      - "/extensions/modules/components"
      - "/interfaces/endpoints/routes"
      - "/paths/urls/links/redirects"
      - "/forwards/responses/errors"
      - "/status/logs/audit"
      - "/tracking/monitoring/alerts"
      - "/books"
      - "/products"
      - "/orders"
      - "/customers"
      - "/inventory/items"
      - "/transactions/sales"
      - "/reviews/products/latest"
      - "/categories/subcategories"
      - "/addresses/validate"
      - "/payments/process/creditcard"
      - "/notifications/push"
      - "/messages/inbox"
      - "/settings/profile"
      - "/cart/items/add"
      - "/wishlist/items/remove"
      - "/profile/preferences/update"
      - "/feedback/suggestions"
      - "/subscriptions/plans"
      - "/billing/invoices/summary"
      - "/events/calendar/upcoming"
      - "/files/documents/downloads"
      - "/support/tickets/create"
      - "/assets/images/gallery"
      - "/roles/permissions/manage"
      - "/licenses/software/activate"
      - "/tags/categories/list"
      - "/search/products/query"
      - "/locales/languages/translate"
      - "/teams/members/add"
      - "/projects/tasks/list"
      - "/calendar/events/schedule"
      - "/groups/threads/discussions"
      - "/threads/comments/post"
      - "/ratings/products/rate"
      - "/rankings/users/top"
      - "/favorites/items/add"
      - "/bookmarks/links/save"
      - "/suggestions/ideas/submit"
      - "/activities/logged/actions"
    upstream:
      nodes:
        "host.docker.internal:8888": 1
      type: roundrobin
#END