services:
  kong:
    image: kong:3.5
    container_name: kong
    restart: always
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong.yaml
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ROUTER_FLAVOR=radix
      - KONG_NGINX_WORKER_PROCESSES=${CPU_CORES:-1}
      - KONG_PROXY_ACCESS_LOG=off
      - KONG_ANONYMOUS_REPORTS=off
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_NGINX_EVENTS_WORKER_CONNECTIONS=65535
      - KONG_NGINX_MAIN_WORKER_RLIMIT_NOFILE=65535
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: root
    volumes:
      - ./src/kong/router/init.lua:/usr/local/share/lua/5.1/kong/router/init.lua
      - ./src/kong/router/radix.lua:/usr/local/share/lua/5.1/kong/router/radix.lua
      - ./src/kong/conf_loader/init.lua:/usr/local/share/lua/5.1/kong/conf_loader/init.lua
      - ./declarative-config/kong-${BENCHMARK_DATA}.yaml:/kong.yaml
    command: >
      bash -c "luarocks install radix-router 0.5.0 && kong start"
